apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    name: producer-service
    app: producer-consumer-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
     name: producer-pod
     app: producer-consumer-app