apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    name: consumer-pod
    app: producer-consumer-app
spec:
  containers:
  - name: emp-consumer
    image: gcr.io/learning-274011/emp-consumer
    ports:
         - containerPort: 80