apiVersion: v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: producer-consumer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer-consumer-app
  template:
    metadata:
      labels:
        name: consumer-pod
        app: producer-consumer-app
    spec:
      containers:
      - name: emp-consumer
        image: gcr.io/learning-274011/k8stest:v1.0
        ports:
        - containerPort: 80